SUPABASE_DB:
  URL: 'https://udilsqbuyyeemrxqgrmk.supabase.co'
  PUB_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQzMTg3Mjc5LCJleHAiOjE5NTg3NjMyNzl9.FLyAzEQRSyfGuqfDQKPk09qpkJVxKPqetDFNulnsfd4'
  SEC_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDMxODcyNzksImV4cCI6MTk1ODc2MzI3OX0.8A-SkPwpnhNEQ39pRtypJQLsjK1R19dHKHVqaJt66QY'

TWITTER_API:
  BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAAPX5YQEAAAAAgqZAUt6fQm%2BzdtskKdxBg92DLFQ%3DyvblO9hDHpyAbcPhqZ7iQTxaGC5I3EUqDOCpv4b5IYUMtZL1nS'